/**
 * Digest rendering — HTML and plain-text email bodies.
 *
 * Format per the PRD:
 *   Account name + one or two bullet-point sentence summaries + hyperlinked source.
 *   AEs know what to do; they don't need a deep dive.
 *
 * The HTML version is what Danielle reads in her inbox.
 * The plain-text version is the fallback for clients that strip HTML.
 */

import type { Signal, Hospital } from '@adonis/shared';

interface HospitalGroup {
  hospital: Hospital;
  signals: Signal[];
}

export function renderDigestText(groups: HospitalGroup[]): string {
  const lines: string[] = [];
  const week = new Date().toISOString().slice(0, 10);
  lines.push(`ADONIS ACCOUNT INTELLIGENCE — WEEK OF ${week}`);
  lines.push('='.repeat(60));
  lines.push('');

  for (const g of groups) {
    lines.push(g.hospital.display_name.toUpperCase());
    lines.push('-'.repeat(g.hospital.display_name.length));
    for (const s of g.signals) {
      const flag = s.priority === 'urgent' ? '[URGENT] ' : '';
      lines.push(`${flag}${s.headline}`);
      lines.push(`  ${s.summary}`);
      lines.push(`  Why: ${s.rationale}`);
      lines.push(`  Source: ${s.source_url}`);
      lines.push('');
    }
    lines.push('');
  }

  lines.push('— Adonis Account Intelligence');
  lines.push('Open the dashboard: https://intel.adonis-prospects.app');
  return lines.join('\n');
}

export function renderDigestHtml(groups: HospitalGroup[]): string {
  const week = new Date().toISOString().slice(0, 10);
  const hospitalBlocks = groups
    .map((g) => {
      const signalRows = g.signals
        .map((s) => {
          const color =
            s.priority === 'urgent' ? '#C0392B' : s.priority === 'standard' ? '#2E6DA4' : '#888';
          const tag = s.priority === 'urgent' ? 'URGENT' : s.priority.toUpperCase();
          return `
            <tr>
              <td style="padding:12px 16px;border-left:3px solid ${color};background:#FAFBFC;">
                <div style="font-size:11px;font-family:monospace;color:${color};letter-spacing:0.08em;text-transform:uppercase;font-weight:700;margin-bottom:4px;">
                  ${tag}
                </div>
                <div style="font-size:15px;font-weight:600;color:#15202B;margin-bottom:6px;">
                  ${escape(s.headline)}
                </div>
                <div style="font-size:13.5px;color:#42566A;line-height:1.5;margin-bottom:8px;">
                  ${escape(s.summary)}
                </div>
                <div style="font-size:13px;color:#1F7A3E;background:#E9F4ED;padding:6px 10px;border-radius:4px;margin-bottom:8px;">
                  <strong>Why it matters:</strong> ${escape(s.rationale)}
                </div>
                <div style="font-size:12px;color:#76889A;">
                  Source: <a href="${escape(s.source_url)}" style="color:#1F6FEB;">${escape(s.source_type)}</a>
                </div>
              </td>
            </tr>`;
        })
        .join('');

      return `
        <table cellpadding="0" cellspacing="0" border="0" width="100%" style="margin-bottom:24px;">
          <tr>
            <td style="padding:14px 16px;background:#16314A;color:#fff;">
              <div style="font-size:18px;font-weight:700;letter-spacing:-0.01em;">
                ${escape(g.hospital.display_name)}
              </div>
              <div style="font-size:12px;color:#A8BBD0;margin-top:2px;">
                ${escape(g.hospital.city ?? '')}${g.hospital.city ? ', ' : ''}${escape(g.hospital.state)} ·
                ${g.signals.length} signal${g.signals.length === 1 ? '' : 's'}
              </div>
            </td>
          </tr>
          ${signalRows}
        </table>`;
    })
    .join('');

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Adonis Account Intelligence — ${week}</title>
</head>
<body style="margin:0;padding:24px;background:#F4F7FA;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#15202B;">
<table cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width:680px;margin:0 auto;background:#fff;border-radius:8px;overflow:hidden;">
  <tr>
    <td style="padding:24px 24px 8px;border-bottom:1px solid #E4E9EF;">
      <div style="font-size:11px;font-family:monospace;letter-spacing:0.16em;color:#1F6FEB;text-transform:uppercase;margin-bottom:4px;">
        Weekly Briefing
      </div>
      <div style="font-size:24px;font-weight:700;color:#16314A;letter-spacing:-0.01em;">
        Account Intelligence — week of ${week}
      </div>
      <div style="font-size:13px;color:#76889A;margin-top:4px;">
        ${groups.length} accounts with activity this week
      </div>
    </td>
  </tr>
  <tr>
    <td style="padding:20px 24px;">
      ${hospitalBlocks}
    </td>
  </tr>
  <tr>
    <td style="padding:16px 24px;background:#F4F7FA;border-top:1px solid #E4E9EF;font-size:12px;color:#76889A;">
      Generated by the Adonis Account Intelligence agent ·
      <a href="https://intel.adonis-prospects.app" style="color:#1F6FEB;">Open the dashboard</a>
    </td>
  </tr>
</table>
</body>
</html>`;
}

function escape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
